#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
force=0

if [ "${1:-}" = "--force" ]; then
    force=1
fi

mkdir -p "$root/memory" "$root/chroma_db" "$root/episodes" "$root/chat" "$root/config"

if [ ! -e "$root/config/local.toml" ]; then
    cp "$root/config/default.toml" "$root/config/local.toml"
fi

if [ ! -e "$root/config/secrets.env" ]; then
    cp "$root/config/secrets.env.example" "$root/config/secrets.env"
    chmod 600 "$root/config/secrets.env"
fi

if [ -f "$root/.env" ] && ! grep -q "Generated by scripts/config_to_env.py" "$root/.env"; then
    cp -n "$root/.env" "$root/.env.legacy"
fi

python_bin="${PYTHON:-python3}"
"$python_bin" "$root/scripts/config_to_env.py" "$root/config/local.toml" "$root" > "$root/.env.tmp"
mv "$root/.env.tmp" "$root/.env"
chmod 600 "$root/.env"

set -a
. "$root/.env"
set +a

# Compile the channel choice into a tiny MeTTa file the agent imports: PeTTa
# can't read env vars into control-flow at runtime. Validate against the known
# set so an unexpected value never lands in a file that gets sourced as code.
channel_kind="${METTACLAW_CHANNEL:-telegram}"
case "$channel_kind" in telegram|irc|mattermost) ;; *) channel_kind=telegram ;; esac
printf ';; Generated by initialize.sh from config/local.toml [channel] kind. Do not edit.\n(= (configureChannel) (configure commchannel %s))\n' "$channel_kind" > "$root/config/channel.metta"

prompt_path="${METTACLAW_PROMPT_PATH:-$root/memory/prompt.txt}"
history_path="${METTACLAW_HISTORY_PATH:-$root/memory/history.metta}"
chroma_dir="${METTACLAW_CHROMA_DIR:-$root/chroma_db}"
mkdir -p "$(dirname "$prompt_path")" "$(dirname "$history_path")" "$chroma_dir"

copy_if_missing() {
    local src="$1"
    local dst="$2"
    if [ "$force" -eq 1 ] || [ ! -e "$dst" ]; then
        cp "$src" "$dst"
    fi
}

copy_if_missing "$root/identity/default-prompt.txt" "$prompt_path"

write_manifest_if_missing() {
    local dst="$root/memory/MANIFEST.toml"
    local owner="${METTACLAW_OWNER:-${USER:-unknown}}"
    local chroma_dir="${METTACLAW_CHROMA_DIR:-$root/chroma_db}"
    local collection="${METTACLAW_CHROMA_COLLECTION:-pettaclaw_ltm}"
    local metric="${METTACLAW_CHROMA_METRIC:-cosine}"
    local embed_model="${METTACLAW_EMBED_MODEL:-}"
    local embed_backend="${METTACLAW_EMBED_BACKEND:-sentence-transformers}"
    local embed_dim="${METTACLAW_EMBED_DIM:-1024}"
    local embed_protocol="${METTACLAW_EMBED_PROTOCOL:-qwen3-embedding-8b-1024-v1}"
    local embed_query_prompt="${METTACLAW_EMBED_QUERY_PROMPT_NAME:-query}"
    local embed_normalized="${METTACLAW_EMBED_NORMALIZE:-1}"
    local source_of_truth="${METTACLAW_MEMORY_SOURCE_OF_TRUTH:-chroma}"
    local index_rebuildable="${METTACLAW_MEMORY_INDEX_IS_REBUILDABLE:-0}"
    local embed_normalized_toml=false
    local index_rebuildable_toml=false
    if [ "$embed_normalized" = "1" ] || [ "$embed_normalized" = "true" ]; then
        embed_normalized_toml=true
    fi
    if [ "$index_rebuildable" = "1" ] || [ "$index_rebuildable" = "true" ]; then
        index_rebuildable_toml=true
    fi
    cat > "$dst" <<EOF
schema_version = 1

store_id = "pettaclaw_ltm_v1"
kind = "claw_memory"
owner = "$owner"
chroma_path = "$chroma_dir"
collection = "$collection"
canonical_source = "$chroma_dir"

embedding_model = "$embed_model"
embedding_backend = "$embed_backend"
embedding_output_dim = $embed_dim
embedding_protocol = "$embed_protocol"
embedding_normalized = $embed_normalized_toml
embedding_query_prompt_name = "$embed_query_prompt"
chroma_metric = "$metric"

source_of_truth = "$source_of_truth"
index_is_rebuildable = $index_rebuildable_toml
write_policy = "local_claw_only"

store_state = "local_only_pending_curated_import"
known_issues = [
  "Historical import should be curated rather than bulk-backfilled.",
  "Enable this local store explicitly in any MCP profile that should query it."
]
EOF
}

write_manifest_if_missing

for f in \
    "$history_path" \
    "$root/memory/LTM.metta" \
    "$root/memory/persistent.metta" \
    "$root/memory/promoted_memories.metta"
do
    [ -e "$f" ] || : > "$f"
done

echo "Initialized pettaclaw runtime files under $root"
echo "Live prompt: $prompt_path"
echo "Private env: $root/.env"
