"""The loop and the command responder both run initialize.sh when they
start. Started together, neither start may fail."""
import os
import pathlib
import shutil
import subprocess
import tempfile
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[1]


class ConcurrentInitialize(unittest.TestCase):
    def test_two_initializers_at_once_both_succeed(self):
        with tempfile.TemporaryDirectory() as home:
            root = pathlib.Path(home) / "agent"
            for directory in ("scripts", "config", "identity"):
                (root / directory).mkdir(parents=True)
            shutil.copy(ROOT / "initialize.sh", root)
            for name in ("config_to_env.py", "render_channel_config.py"):
                shutil.copy(ROOT / "scripts" / name, root / "scripts")
            for name in ("default.toml", "secrets.env.example"):
                shutil.copy(ROOT / "config" / name, root / "config")
            (root / "identity" / "default-prompt.txt").write_text("prompt\n")
            env = {key: value for key, value in os.environ.items()
                   if not key.startswith("METTACLAW_")}
            env["HOME"] = home
            for _ in range(10):
                starts = [subprocess.Popen(
                    ["bash", str(root / "initialize.sh")], env=env,
                    stdout=subprocess.DEVNULL, stderr=subprocess.PIPE,
                    text=True) for _ in range(2)]
                for start in starts:
                    _, errors = start.communicate(timeout=120)
                    self.assertEqual(start.returncode, 0, errors)
            self.assertIn("Generated by scripts/config_to_env.py",
                          (root / ".env").read_text())
            self.assertEqual(oct((root / ".env").stat().st_mode & 0o077), "0o0")
            self.assertTrue((root / "config" / "channel.metta").read_text())
            leftovers = [p.name for p in list(root.glob(".env.tmp*")) +
                         list((root / "config").glob("channel.metta.tmp*"))]
            self.assertEqual(leftovers, [])


if __name__ == "__main__":
    unittest.main()
