#!/usr/bin/env python3
import os
import sys

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11
    import tomli as tomllib


def expand(value, root):
    if not isinstance(value, str):
        return value
    env = dict(os.environ)
    env.setdefault("HOME", os.path.expanduser("~"))
    env.setdefault("USER", os.environ.get("USER", ""))
    env["ROOT"] = root
    old = os.environ.copy()
    try:
        os.environ.clear()
        os.environ.update(env)
        return os.path.expanduser(os.path.expandvars(value))
    finally:
        os.environ.clear()
        os.environ.update(old)


def shell_quote(value):
    return "'" + str(value).replace("'", "'\"'\"'") + "'"


def bool_env(value):
    return "1" if bool(value) else "0"


def emit(key, value):
    if value is None or value == "":
        return
    if isinstance(value, bool):
        value = bool_env(value)
    elif isinstance(value, list):
        value = ",".join(str(item) for item in value)
    print(f"export {key}={shell_quote(value)}")


def main():
    if len(sys.argv) != 3:
        print("usage: config_to_env.py <config.toml> <repo-root>", file=sys.stderr)
        return 2
    config_path, root = sys.argv[1], os.path.abspath(sys.argv[2])
    with open(config_path, "rb") as f:
        config = tomllib.load(f)

    paths = config.get("paths", {})
    agent = config.get("agent", {})
    channel = config.get("channel", {})
    telegram = config.get("telegram", {})
    search = config.get("search", {})
    memory = config.get("memory", {})

    print("# Generated by scripts/config_to_env.py. Do not edit directly.")
    print("# Edit config/local.toml and config/secrets.env instead.")

    # CeTTaClaw runs on the CeTTa interfaces binary at CETTA_ROOT (CeTTa proper),
    # not on PeTTa. Memory is an out-of-process HTTP shim; MCP is a spawned
    # Python bridge shipped with the agent adapter.
    emit("CETTA_ROOT", expand(paths.get("cetta_root"), root))
    emit("METTACLAW_MEMORY_ENDPOINT", expand(paths.get("memory_endpoint"), root))
    emit("METTACLAW_MCP_PYTHON", expand(paths.get("mcp_python"), root))
    emit("METTACLAW_MCP_BRIDGE_CLI", expand(paths.get("mcp_bridge_cli"), root))
    emit("METTACLAW_CHROMA_DIR", expand(paths.get("chroma_dir"), root))
    emit("METTACLAW_TELEGRAM_OFFSET_PATH", expand(paths.get("telegram_offset_path"), root))
    emit("METTACLAW_TELEGRAM_LOG_PATH", expand(paths.get("telegram_log_path"), root))
    emit("METTACLAW_PROMPT_PATH", expand(paths.get("prompt_path"), root))
    emit("METTACLAW_HISTORY_PATH", expand(paths.get("history_path"), root))
    emit("METTACLAW_MEMORY_LOG_DIR", expand(paths.get("memory_log_dir"), root))
    emit("METTACLAW_REPOS_DIR", expand(paths.get("repos_dir"), root))
    emit("METTACLAW_EMBED_MODEL", expand(paths.get("embed_model"), root))

    emit("METTACLAW_OWNER", expand(agent.get("owner"), root))
    emit("METTACLAW_HEARTBEAT_INTERVAL_SECONDS", agent.get("heartbeat_interval_seconds"))
    emit("SYNTHETIC_MODEL", agent.get("synthetic_model"))
    emit("SYNTHETIC_BASE_URL", agent.get("synthetic_base_url"))

    emit("METTACLAW_CHANNEL", channel.get("kind"))

    emit("METTACLAW_TELEGRAM_ALLOW_PRIVATE", telegram.get("allow_private"))
    emit("METTACLAW_TELEGRAM_ALLOWED_CHAT_IDS", telegram.get("allowed_chat_ids"))

    emit("METTACLAW_SEARCH_PROVIDER", search.get("provider"))

    emit("METTACLAW_CHROMA_COLLECTION", memory.get("collection"))
    emit("METTACLAW_CHROMA_METRIC", memory.get("metric"))
    emit("METTACLAW_EMBED_BACKEND", memory.get("embed_backend"))
    emit("METTACLAW_EMBED_PROTOCOL", memory.get("embed_protocol"))
    emit("METTACLAW_EMBED_DIM", memory.get("embed_dim"))
    emit("METTACLAW_EMBED_DEVICE", memory.get("embed_device"))
    emit("METTACLAW_EMBED_QUERY_PROMPT_NAME", memory.get("embed_query_prompt_name"))
    emit("METTACLAW_EMBED_NORMALIZE", memory.get("embed_normalize"))
    emit("METTACLAW_EMBED_MAX_TOKENS", memory.get("embed_max_tokens"))
    emit("METTACLAW_MEMORY_SOURCE_OF_TRUTH", memory.get("source_of_truth"))
    emit("METTACLAW_MEMORY_INDEX_IS_REBUILDABLE", memory.get("index_is_rebuildable"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
